### ISSUE TITLE
By extracting the spectra a small missmatch between the shape of flux_sum and flux_mean is detected

### ISSUE THREAD

**Issue by HannaKellermann** [wangleon/gamse#53]
By extracting a spectrum a small but notable difference between the shape of flux_sum and flux_mean is detected which should NOT be there (hight difference would be ok but shape difference is a problem) To get a better idea of the problem I attached the following image. The problem is always in the flux_sum and it randomly appears on different orders. To create the imageI did the following (with g beeing the sextracted pectrum):
g['A'][a]['flux_mean']/np.max(g['A'][a]['flux_mean'])-g['A'][a]['flux_sum']/np.max(g['A'][a]['flux_sum']

![grafik](https://user-images.githubusercontent.com/49488552/99535263-f402c980-29a8-11eb-9ac6-9dc8631eef93.png)

**Comment by wangleon** [comment]
Reason:

The upper boundary of sum extraction in echelle.extract.extract_aperset() is one pixel missing. it is appears only near dy/dx = 0

![A_033](https://user-images.githubusercontent.com/1935825/99699100-8bad0880-2acc-11eb-9f93-60a268337ba7.png)

left: comparison of flux_sum and flux_mean. right: n_sum


A closer look into the summing mask:


```
#!/usr/bin/env python3
import numpy as np
import astropy.io.fits as fits
import matplotlib.pyplot as plt
from gamse.echelle.trace import load_aperture_set

data = fits.getdata('flat_A.fits')
aperset = load_aperture_set('trace_A.trc')
ny, nx = 2048, 2048
yy, xx = np.mgrid[:ny:,:nx:]
allx = np.arange(nx)
position = aperset[38].position(allx)
lower_limit = 6
upper_limit = 6
lower_line = position - lower_limit
upper_line = position + upper_limit
lower_line = np.maximum(lower_line, -0.5)
lower_line = np.minimum(lower_line, ny-1-0.5)
upper_line = np.maximum(upper_line, -0.5)
upper_line = np.minimum(upper_line, ny-1-0.5)
lower_ints = np.int32(np.round(lower_line))
upper_ints = np.int32(np.round(upper_line))
m1 = yy[:,:] > lower_ints
m2 = yy[:,:] < upper_ints
newmask = np.zeros_like(data, dtype=np.bool)
newmask[:,:] = m1*m2
newmask = np.float32(newmask)
newmask[lower_ints, allx] = 1-(lower_line+0.5)%1
newmask[upper_ints, allx] = (upper_line+0.5)%1

r1 = int(lower_line.min())
r2 = int(upper_line.max())+1
print(lower_line.min(), int(lower_line.min()), r1)
print(upper_line.max(), int(upper_line.max()), r2)
weight_sum = newmask[r1:r2].sum(axis=0)


fig = plt.figure(dpi=200)
ax = fig.add_subplot(211)
ax2 = fig.add_subplot(212)
ax.imshow(newmask, origin='lower', aspect='auto')
ax.axhline(y=r1, color='b', ls='--', lw=0.5)
ax.axhline(y=r2, color='r', ls='--', lw=0.5)
ax2.plot(newmask.sum(axis=0))
ax2.plot(weight_sum)
ax.set_xlim(1000, 1500)
ax.set_ylim(1165, 1205)

ax2.set_xlim(1000, 1500)
ax2.set_ylim(9, 15)
plt.show()
```

![check_boundary](https://user-images.githubusercontent.com/1935825/99698880-44bf1300-2acc-11eb-9b9a-6fe86043d2d4.png)


solution: 
```
r1 = int(lower_line.min())
r2 = int(np.ceil(upper_line.max()))+1
```
